---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-movie-api-dynamodb
  namespace: movie-search
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: movie-search-dynamodb
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: movie-search-dynamodb
    spec:
      serviceAccountName: movie-search
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: 652391548090.dkr.ecr.us-east-2.amazonaws.com/movie-app:v7
          imagePullPolicy: Always
          name: api-dynamodb
          ports:
            - containerPort: 3000 # match with expose port in dockerfile
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - NET_RAW
                - ALL
          env:
            - name: tableName # match with your dynamodb table setting
              value: movie-details-table
            - name: aws_region
              value: us-east-2
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: service-movie-api-dynamodb
  namespace: movie-search
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: movie-search-dynamodb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-movie-api-dynamodb
  namespace: movie-search
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-movie-api-dynamodb
                port:
                  number: 80
